### PR TITLE
Add sample perf results image.

### PR DESCRIPTION
**Pull request by pmaytak**
MS Learn docs only support tables of maximum 4 columns. So added a table image instead.

### CODE REVIEW

**Comment by localden** [comment]
@pmaytak for accessibility and scalability (mobile/small screen devices), we should not be replacing text tables with images.

**Comment by pmaytak** [comment]
> @pmaytak for accessibility and scalability (mobile/small screen devices), we should not be replacing text tables with images. Let me see how to fix this.

Yea, if there's a workaround, that'd be great. Otherwise, I figured including an image would be better than not including anything at all. However, I could just link to a PR that has test results, that would work also.

**Comment by localden** [comment]
Fixed by #253.

**Comment by pmaytak** [comment]
> Fixed by #253.

@localden Thanks. Hmm, so the fix is just having column alignment on all columns?...

**Comment by localden** [comment]
@pmaytak yep, and it needed a whitespace. The warning is just that - a warning. They _recommend_ keeping it under 4, but it generally is possible to have more, just to not overuse them.

**Pull request closed without merging**
