### PR TITLE
Attempt to add Abstractions

### PR DESCRIPTION
**Pull request by jmprieur**

### CODE REVIEW

**Comment by localden** [comment]
@jmprieur any luck with the changes to the path to the samples?

**Comment by jmprieur** [comment]
@localden: I was just waiting for you to approve the PR

**Comment by localden** [comment]
@jmprieur just checking - were the sample paths updated in the source repo, so they don't conflict with other existing samples?

**Comment by jmprieur** [comment]
@localden this is what I've been trying to do:
https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/compare/jmprieur/referenceDoc?expand=1

so far there was no sample in abstractions, but I would like to add them

**Comment by jmprieur** [comment]
Closing as it was done in https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/pull/110/files

**Pull request closed without merging**
